### PR TITLE
MPC-HC Suffix

### PR DESCRIPTION
**Pull request by kurdtkobain**
add a custom suffix to mpc-hc should not effect other handlers(not tested)
EDIT: oops has #13 in it as well, it requires it anyway

### CODE REVIEW

**Comment by pendo324** [comment]
Hey man, thanks for contributing :). 

I'll take a look at your commits some time this weekend (I've been really busy for some time now, hence the 12 issues lol), but I do remember adding some features to the GUI which should still be on my computer, uncommitted. 

So hopefully when I push that commit, your merge will still have no conflicts.

**Comment by pendo324** [comment]
@kurdtkobain looks like there's a merge conflict. If you could pull from master and update, that would be greatly appreciated.

**Comment by kurdtkobain** [comment]
Had to remove suffix text for now i will try to add back when i get the time, should have no conflicts now.

**Comment by kurdtkobain** [comment]
just merge #13 i will redo this later.

**Pull request closed without merging**
